"""Offline, integer-only ANC parameter/convergence analysis.

This is a synthetic identity-secondary-path experiment. It is not an
acoustic, codec, board, or plant measurement.
"""
from __future__ import annotations

import csv
import math
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from golden_reference import CoreModel, MAX16, MAX24, MIN16, MIN24  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
REPORT = ROOT / "docs" / "offline_anc_analysis.md"
CSV = BUILD / "offline_anc_mu_sweep.csv"
N = 4096
WINDOW = 512
SEED = 0x5EED2026
TRUE_COEFF = (8192, -4096, 2048, 1024)
MU_VALUES = (0, 32, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32767, 65535)


def rms(values):
    return math.sqrt(sum(v * v for v in values) / len(values))


def synthetic_reference():
    rng = random.Random(SEED)
    history = [0] * len(TRUE_COEFF)
    for k in range(N):
        x = rng.randint(-8192, 8192)
        if k % 7 == 0:
            x += rng.randint(-4096, 4096)
        x = max(-20000, min(20000, x))
        history = [x] + history[:-1]
        desired = sum(history[i] * TRUE_COEFF[i] for i in range(len(TRUE_COEFF))) >> 15
        yield x, desired


def run_mu(mu):
    model = CoreModel()
    errors = []
    for x, desired in synthetic_reference():
        # Predict from the pre-update state; sample() then performs the exact
        # RTL-matched output, update, and delay transition.
        acc = sum((x if i == 0 else model.delay[i - 1]) * model.coeff[i]
                  for i in range(len(model.coeff)))
        output = max(MIN24, min(MAX24, acc >> 15))
        error = desired - output
        model.sample(x, error, True, False, mu)
        errors.append(error)
    first = rms(errors[:WINDOW])
    last = rms(errors[-WINDOW:])
    db = 20.0 * math.log10(first / last) if last else float("inf")
    coeff_rmse = math.sqrt(sum((model.coeff[i] - (TRUE_COEFF[i] if i < len(TRUE_COEFF) else 0)) ** 2
                               for i in range(len(model.coeff))) / len(model.coeff))
    return {
        "mu_q15": mu,
        "initial_rms": first,
        "final_rms": last,
        "change_db": db,
        "coeff_rmse": coeff_rmse,
        "clip_count": model.clips,
        "sample_count": model.samples,
        "final_coeff0": model.coeff[0],
        "final_coeff1": model.coeff[1],
        "final_coeff2": model.coeff[2],
        "final_coeff3": model.coeff[3],
    }


def saturation_probe():
    model = CoreModel()
    model.write_coeff(0, MAX16 + 123)
    model.write_coeff(1, MAX16 + 123)
    model.write_coeff(2, MIN16 - 123)
    for _ in range(2):
        model.sample(MAX24, 0, True, False, 0)
    return model.coeff[0], model.coeff[2], model.clips, model.samples


def write_outputs(rows):
    BUILD.mkdir(exist_ok=True)
    REPORT.parent.mkdir(exist_ok=True)
    with CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    stable = [r for r in rows if r["change_db"] > 0]
    coeff_hi, coeff_lo, sat_clips, sat_samples = saturation_probe()
    best = max(rows, key=lambda r: r["change_db"])
    lines = [
        "# Offline ANC parameter and convergence analysis",
        "",
        "## Scope and evidence boundary",
        "",
        "- This report is generated by `scripts/offline_anc_analysis.py` using the integer `CoreModel`.",
        "- The reference and desired response are synthetic; the secondary path is the RTL MVP's identity path.",
        "- Samples/coefficient values are signed integer containers under the Q15 contract; no volts, pascals, codec, room, or board data are used.",
        "- Results describe this finite deterministic experiment only, not acoustic cancellation, global stability, or a hardware recommendation.",
        "",
        "## Reproducible setup",
        "",
        f"- Samples: `{N}`; RMS window: `{WINDOW}`; random seed: `0x{SEED:X}`.",
        f"- Synthetic target FIR (Q15 integers): `{list(TRUE_COEFF)}`; input clamp: `[-20000, 20000]`.",
        f"- Tested `mu_q15`: `{list(MU_VALUES)}`; adaptation enabled; bypass disabled.",
        "- For each sample: generate reference/desired, calculate pre-update FIR output, set `error=desired-output`, then execute the exact integer model transition.",
        "",
        "## Sweep results",
        "",
        "| mu_q15 | initial RMS | final RMS | change (dB) | coefficient RMSE | clips | samples |",
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(f"| {r['mu_q15']} | {r['initial_rms']:.3f} | {r['final_rms']:.3f} | {r['change_db']:.3f} | {r['coeff_rmse']:.3f} | {r['clip_count']} | {r['sample_count']} |")
    lines += [
        "",
        f"Observed positive finite-window RMS change for `{len(stable)}/{len(rows)}` tested values; the largest observed change was `mu_q15={best['mu_q15']}` at `{best['change_db']:.3f} dB`.",
        "These are descriptive observations from the stated seed, length, target, and identity path. They are not a proof of monotonicity or convergence outside this experiment.",
        "",
        "## Boundary checks",
        "",
        f"- Coefficient write saturation: writes `{MAX16 + 123}` and `{MIN16 - 123}` yielded `{coeff_hi}` and `{coeff_lo}`; expected range is `[{MIN16}, {MAX16}]`.",
        f"- Output boundary stress: two full-scale samples with the saturated positive coefficient produced `clip_count={sat_clips}` over `sample_count={sat_samples}`.",
        "- The normal sweep had no output clips; this indicates only that its selected synthetic amplitudes stayed inside the 24-bit output range.",
        "",
        "## Interpretation and next validation",
        "",
        "- The sweep supports using a small-to-moderate `mu_q15` as the next simulation candidate, while the larger tested values require caution because their finite-window error worsened here.",
        "- Before any hardware claim, replace the identity secondary path with an identified/measured path, test disturbances and quantization/noise, run longer and multi-seed trials, and verify FPGA timing/resource reports.",
        "- Acoustic A/B reduction, codec configuration, pin assignment, bitstream execution, and physical stability remain unverified.",
        "",
        "## Evidence files",
        "",
        f"- CSV: `{CSV.relative_to(ROOT)}`",
        "- Generator: `scripts/offline_anc_analysis.py`",
        "",
    ]
    REPORT.write_text("\n".join(lines), encoding="utf-8")


def main():
    rows = [run_mu(mu) for mu in MU_VALUES]
    write_outputs(rows)
    coeff_hi, coeff_lo, clips, samples = saturation_probe()
    assert MIN16 <= coeff_lo <= MAX16 and MIN16 <= coeff_hi <= MAX16
    assert clips > 0 and samples == 2
    print(f"OFFLINE_ANC_ANALYSIS_PASS rows={len(rows)} samples_per_row={N}")
    print(f"SATURATION_PROBE_PASS coeff_hi={coeff_hi} coeff_lo={coeff_lo} clips={clips} samples={samples}")
    print(f"REPORT={REPORT}")
    print(f"CSV={CSV}")


if __name__ == "__main__":
    main()
